# Generated by Django 4.2.30 on 2026-06-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fats_g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('kcal_consumed', models.IntegerField(default=0)),
                ('kcal_target', models.IntegerField(default=2000)),
            ],
        ),
        migrations.CreateModel(
            name='HydrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_ml', models.IntegerField(default=0)),
            ],
        ),
    ]
