# Generated by Django 4.2.30 on 2026-06-10 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydration_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailynutrition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hydrationlog',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailynutrition',
            unique_together={('user', 'date')},
        ),
    ]
