# Generated by Django 4.2.30 on 2026-06-10 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttemplate',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness.workouttemplate'),
        ),
        migrations.AddField(
            model_name='bodymetrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to=settings.AUTH_USER_MODEL),
        ),
    ]
